config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'homes/index'
  get "up" => "rails/health#show", as: :rails_health_check
  root "homes#index"
  resources "members"
  resources "homes"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
  attribute :service, :integer, default: 0

  # Enum mapping
  SERVICES = { homesitting: 0, housesitting: 1, dvisits: 2 }.freeze

  # Validate presence of service and other attributes
  validates :service, inclusion: { in: SERVICES.values }
  validates :dob, presence: true
  validates :edod, presence: true
  validates :animal_type, presence: true
  validates :costmaxmin, presence: true
  validates :scales, inclusion: { in: [true, false] }
  validates :yard, inclusion: { in: [true, false] }
  validates :no_dog, inclusion: { in: [true, false] }
  validates :no_cat, inclusion: { in: [true, false] }
  validates :one_client, inclusion: { in: [true, false] }
  validates :non_neutered_dogs, inclusion: { in: [true, false] }
end

app/models/member.rb
class Member < ApplicationRecord
  has_rich_text :content


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @home = Home.all

  end

  def new
    @home = Home.new

  end

  def show
    @home = Home.find(params[:id])
  end

  def create
    @home = Home.new(home_params)
      if @home.save
        redirect_to @home, notice: "Message sent successfully!"
      else
        render :new
      end
  end

  def edit
    @home = Home.find(params[:id])
    if @home.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end

  end

  def destroy

  end

  private
  def home_params
    params.require(:home).permit(:homesitting, :housesitting, :dvisits, :dob, :edod, :dogs, :cat, :costmaxmin, :scales, :yard, :no_dog, :no_cat, :one_client, :non_neutered_dogs)

  end


end

app/controllers/members_Controller.rb
class MembersController < ApplicationController
  def index
    @member = Member.all

  end

  def new
    @member = Member.new
  end

  def show
    @member = Member.find(params[:id])

  end


  def create
    @member = Member.new(member_params)
      if @member.save
        redirect_to members_path
      else
         render :new, status: :unprocessable_entity
      end
  end

  def edit
    @member = Member.find(params[:id])
    if @member.save
      redirect_to root_path
    else
     render :new, status: :unprocessable_entity
    end

  end

  def destroy
    @member.destroy
    redirect_to root_path
  end

  private

  def member_params
    params.require(:member).permit(:name, :email, :date_of_birth, :content, :reference, :address)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @member = Member.all

  end

  def new
    @member = Member.new
  end

  def show

  end


  def create
    @member = Member.new(member_params)
      if @member.save
        redirect_to members_path
      else
         render :new, status: :unprocessable_entity
      end
  end

  def edit
    @member = Member.find(params[:id])
    if @member.save
      redirect_to root_path
    else
     render :new, status: :unprocessable_entity
    end

  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
      redirect_to root_path, notice: "Member was successfully deleted."
    else
      redirect_to root_path, alert: "Unable to find member."
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :email, :date_of_birth, :content, :reference, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/homes/_form.html.erb
<div style="position: relative; display: flex; justify-content: center; align-items: center; text-align: center;">
  <%= image_tag "allimg/small.jpg", width: "auto", height: "auto", style: "max-width: 100%; height: auto;" %>
  <div style="position: absolute; top: 15%; left: 0; width: 100%; height: 100%;">
    <%= form_with(model: @home, url: homes_path, method: "post", style: "color: black;") do |f| %>
      <fieldset>
        <legend><h2>Service</h2></legend>
        <%= f.radio_button :service, :homesitting, id: "homesitting" %>
        <%= f.label :homesitting, "Boarding In Sitters Home" %>
        <%= f.radio_button :service, :housesitting, id: "housesitting" %>
        <%= f.label :housesitting, "House Sitting" %>
        <%= f.radio_button :service, :dvisits, id: "dvisits" %>
        <%= f.label :dvisits, "Drop in Visits" %>
      </fieldset>
      <br>
      <div>
        <%= f.label :dob, "Drop Off" %>
        <%= f.date_field :dob %>
        <%= f.label :edod, "Pick up" %>
        <%= f.date_field :edod %>
      </div>
      <br>
      <div>
        <%= f.check_box :animal_types, { multiple: true }, "dog" %>
        <%= f.label :dog, "Dog" %>
        <%= f.check_box :animal_types, { multiple: true }, "cat" %>
        <%= f.label :cat, "Cat" %>
      </div>
      <br>
      <div>
        <%= f.label :costmaxmin, "Rate per night! $1 to $250" %>
        <%= f.range_field :costmaxmin, min: 1, max: 250, step: 1 %>
      </div>
      <br>
      <fieldset>
        <legend>Housing Features</legend>
        <div>
          <%= f.check_box :housing_features, { multiple: true }, "scales" %>
          <%= f.label :scales, "Has House (excludes Apartment)" %>
        </div>
        <div>
          <%= f.check_box :housing_features, { multiple: true }, "yard" %>
          <%= f.label :yard, "Has Fenced yard" %>
        </div>
      </fieldset>
      <br>
      <fieldset>
        <legend>Pets at home</legend>
        <div>
          <%= f.check_box :pets_at_home, { multiple: true }, "no_dog" %>
          <%= f.label :no_dog, "Doesn't own a dog" %>
        </div>
        <div>
          <%= f.check_box :pets_at_home, { multiple: true }, "no_cat" %>
          <%= f.label :no_cat, "Doesn't own a cat" %>
        </div>
        <div>
          <%= f.check_box :pets_at_home, { multiple: true }, "one_client" %>
          <%= f.label :one_client, "Accepts Only one client at a time" %>
        </div>
        <div>
          <%= f.check_box :pets_at_home, { multiple: true }, "non_neutered_dogs" %>
          <%= f.label :non_neutered_dogs, "Accepts non neutered male dogs" %>
        </div>
      </fieldset>
      <br>
      <%= f.submit "Submit" %>
    <% end %>
  </div>
</div>

app/views/homes/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" <%= link_to "Wooffin", root_path%></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Our Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Become a sitter", members_path%></a>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Sign In</a> %>
          <a class="nav-link" <%= link_to "Sign In", new_user_session_path %> </a>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="#">Sign Up</a> %>
          <a class="nav-link" <%= link_to "Sign Up", new_user_registration_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help?</a>
          <%# < class="nav-link" <%= link_to "Help", %> 
        </li>
       
      </ul>
    </div>
  </div>
</nav>

app/views/homes/index.html.erb
<%= render partial: "form" %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wooffin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'homes/header'%>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with model: @member do |form|%>

    <div>
        <%= form.label :name%>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <div>
        <%= form.label :date_of_birth%>
        <%= form.date_field :date_of_birth%>
    </div>
    <div>
        <%= form.label :content%>
        <%= form.rich_text_area :content%>
    </div>
    <div>
        <%= form.label :Reference %>
        <%= form.text_field :reference%>
    </div>
    <div>
        <%= form.label :Address%>
        <%= form.text_field :address%> 
    </div>
    <div>
        <%= form.label :PostCode%>
        <%= form.text_field :postcode %>
    </div>                    
  <%= form.button%>

<% end %>

app/views/members/edit.html.erb
<h1>Edit Member Profile</h1>

<%= render partial: "form", locals: {member: @member}%>

<%= button_to "Delete", @member, method: :delete, data: {turbo_confrm: "Are You Sure?"} %>

app/views/members/index.html.erb
<div style="position: relative; display: flex; justify-content: center; align-items: center; text-align: center;">
  <%= image_tag "allimg/blackandwhite.jpg", width: "auto", height: "auto", style: "max-width: 100%; height: auto;" %>
  <div style="position: absolute; color: yellow; font-size: 24px; font-weight: bold; top: 55%;">
        <h3>Get Paid to Play with Pets</h3>
        <h5 style="color: White">Wooffin makes it easy and promotes you to the world’s largest network of pet parents.</h5>
        <a <%= link_to "Get Started", new_member_path%></a>
  </div>
</div>

app/views/members/new.html.erb
<div class="container">


<h1>New Member Area</h1>

<%= render partial: "form", locals: {member: @member}%>

</div>

app/views/members/show.html.erb
<div class="container">

<h1>Show Memeber Details</h1>

<%= render partial: "form", locals: {member: @member}%>

<%= button_to "Delete", @member, method: :delete, data: {turbo_confrm: "Are You Sure?"} %>

</div>